apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: {{ .Values.namespace }}
  labels:
    app: nessie
    {{- include "iceberg-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 19120
      targetPort: 19120
      protocol: TCP
  selector:
    app: nessie
