apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "iceberg-stack.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.minio.accessKey }}
  secret-key: {{ .Values.minio.secretKey }}
