apiVersion: v2
name: iceberg-stack
description: A Helm chart for deploying MinIO, Nessie (Iceberg REST Catalog), and DuckDB
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - iceberg
  - duckdb
  - minio
  - nessie
  - data-lake
maintainers:
  - name: telemetry-lake
